docs: blocklet ui
blocklet/blocklet-site pull request #34
Opened 2022-09-25 09:27 UTC by donotlb

### 关联 Issue

- https://github.com/ArcBlock/blocklet-server/issues/5370

### 主要改动

添加 blocklet ui 文档

### 界面截图

![image](https://user-images.githubusercontent.com/24994263/192136936-d7bebaff-b66d-426e-9469-93717dc2fac2.png)

### 检查清单

- [x] 本次变更验证了 developer-site：本地启动，访问正常

2022-09-25 23:01 UTC, wangshijun requested changes

2022-09-26 01:56 UTC, donotlb commented on developer/docs/pages/reference/blocklet-ui/index.md
> +import Header from '@blocklet/ui-react/lib/Header';
注入 provider 的部分 在后面的 "Header 内置 Addons" 章节里讲了

2022-09-26 02:57 UTC, linchen1987 commented on developer/docs/pages/reference/blocklet-ui/index.md
> +- did
did -> appId

2022-09-26 03:07 UTC, donotlb commented on developer/docs/pages/reference/blocklet-ui/index.md
> +- did
已处理，问一下，blocklet ui header 中显示 app did 用的是 metajs 中的 did 字段，是否要改成 appId ？

2022-09-26 08:09 UTC, wangshijun approved these changes

2022-09-26 08:18 UTC, linchen1987 commented on developer/docs/pages/reference/blocklet-ui/index.md
> +- did
需要改成 appId

2022-09-26 08:19 UTC, linchen1987 approved these changes

2022-09-26 08:19 UTC, merged