WIP feat: improve blocklet bundle docs
blocklet/blocklet-site pull request #60
Opened 2022-10-17 15:00 UTC by skypesky

### 关联 Issue

### 主要改动

### 界面截图

### 检查清单

- [ ] 本次变更验证了 blocklet-site：本地启动，访问正常
- [ ] 本次变更验证了 developer-site：本地启动，访问正常
- [ ] 本次变更中有添加或更新 npm 依赖，并且没有导致同 1 个依赖出现多个版本【检查 yarn.lock 的 diff】

2022-10-17 22:15 UTC, wangshijun requested changes
你这个提纲不太对，不是讲打包的，相关的话题在 https://store.blocklet.dev/docs/en/detail/images 有覆盖，讲打包的时候应该就是对不同类型的 blocklet，不同类型的 repo，如何打包，如何处理打包的常见问题。

2022-10-18 01:53 UTC, skypesky commented
@wangshijun 

我的理解是: 
在 bundle 之前应该告诉用户应该准备哪些东西，哪些是必须要有的，哪些是可选的。不然 bundle 的时候，就会发现缺少一些东西，总是报错。
其次，在 bundle 的时候，如果还要用户自定义的 bundle 自己的指令的话，那么前面 `blocklet create ${blocklet-name}` 就全部白讲了，因为用户只会通过 `bloklet create` 来创建 blocklet, 而通过 `blocklet create` 创建的 blocklet 刚好默认就已经有直接可用的 bundle, deploy 命令了。
最后，对不同类型的 blocklet，不同类型的 repo，如何打包，已经脱离了普通 bundle 的范畴，似乎是 bundle 进阶的指南了。

2022-10-18 02:07 UTC, LancelotLewis commented
单独从 bundle 这一功能来讲的话，可以借助 3W1H 来分析：

1. What -> 打包功能是什么？简单介绍一下打包的工作原理
2. Why -> 为什么需要打包？deploy 及 upload 都依赖于打包，打包能带来的作用
3. Where -> （感觉不需要这一点）
4. How -> 怎么去打包？
   - 链接到 Create Blocklet 中的 bundle 说明
   - 针对不同类型应用给出手动添加打包命令的说明

2022-10-18 02:12 UTC, linchen1987 commented
提纲中的 “定义需要打包的文件” 是必要的，应该保留。

但是还却其他的内容。

- 如何直接使用 blocklet bundle 打包 blocklet, blocklet bundle 做了什么
- 哪些文件被打包了，包结构
- 不同场景下如何使用 blocklet bundle  ( create-release, zip bundle, menorepo 等)

直接使用 npm run bundle 是在 create-blocklet ， get started ，tutorial  这类文档中使用

2022-10-18 02:14 UTC, wangshijun commented
> 那么前面 `blocklet create ${blocklet-name}` 就全部白讲了，因为用户只会通过 `bloklet create` 来创建 blocklet, 而通过 `blocklet create` 创建的 blocklet 刚好默认就已经有直接可用的 bundle, deploy 命令了。

实际上用不不总是全部用 create-blocklet，他可能需要把自己现有的项目转为 blocklet，那个时候就需要自己搞定 bundle script，这个文档应该能帮助其搞定这个事情。

我建议把文档结构调整为：

- Bundle 简介：是什么？结构如何？
- Bundle 准备工作：jianchao 之前计划些的部分
- Bundle 进行时
	- 打包从 create-blocklet 或 blocklet create 创建的项目
	- 使用不同的模式打包
		-  zip
		- webpack 不建议使用了
		- 自动选择模式的逻辑
	- 为不同的代码组织方式打包
		- 打包单个应用
		- 打包 monorepo 中的应用

2022-10-23 03:07 UTC, wangshijun requested changes

2022-10-23 03:07 UTC, wangshijun commented on developer/docs/pages/how-to/bundle/index.zh.md
> +│   ├── dist
这里可以只保留关键的，去掉噪音

2022-10-23 03:07 UTC, wangshijun commented on developer/docs/pages/how-to/bundle/index.zh.md
> +你需要打包你的 blocklet，才能将 blocklet 发布到 `blocklet store` 和 部署到 `blocklet server`。
这里还可以再展开下，store 和 server 分发和消费的软件包要遵循相同的格式，最好列几个类比，比如 npm，apk，ipa 等

2022-10-23 03:07 UTC, wangshijun commented on developer/docs/pages/how-to/bundle/index.zh.md
> +main: api/index.js
main 字段的更多解释应该连接到 types，因为不同类型的 main 指向不同

2022-10-23 03:07 UTC, wangshijun commented on developer/docs/pages/how-to/bundle/index.zh.md
> +每个 blocklet 都应该有自己的使用文档，简单易上手的使用文档更能吸引用户去使用它。
这里可以列举下应该在 blocklet.md 里面放哪些内容，再给几个例子的链接

2022-10-23 03:07 UTC, wangshijun commented on developer/docs/pages/how-to/bundle/index.zh.md
> +每次更新 blocklet 的时候，我们可能需要记录变更的日志。
可以附一张截图来说明 changlog 如何展示的

2022-10-23 03:07 UTC, wangshijun commented on developer/docs/pages/how-to/bundle/index.zh.md
> +2. 将打包后的文件放在项目根目录下 `.blocklet/release` 目录
最后加上打包之后可以做什么，比如发布，远程部署，给出链接

2022-10-23 12:42 UTC, skypesky commented on developer/docs/pages/how-to/bundle/index.zh.md
> +每个 blocklet 都应该有自己的使用文档，简单易上手的使用文档更能吸引用户去使用它。
ok，能给的例子都给 test store 的 blocklet 链接了，视频的例子现在好像还没有，之后再贴吧

2022-10-24 06:28 UTC, skypesky commented on developer/docs/pages/how-to/bundle/index.zh.md
> +main: api/index.js
我思考了一下，这里有个疑惑，不同的类型如果是 blocklet create 创建的，那就不需要修改 main 字段，也不需要特别说明。
如果是用户使用了 blocklet create 之外的模板或框架，又无法给出具体的方案，每个入口其实都是不一样的，自定义的。

2022-10-25 01:46 UTC, wangshijun approved these changes

2022-10-25 01:46 UTC, merged